# Generated by Django 4.0.4 on 2022-05-27 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mark', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Range',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultnumber', models.IntegerField()),
                ('result', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Restoration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('total_price', models.FloatField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.car')),
            ],
        ),
        migrations.CreateModel(
            name='RangeVoteAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restoration1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restoration1', to='app.restoration')),
                ('restoration2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restoration2', to='app.restoration')),
                ('restoration3', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restoration3', to='app.restoration')),
                ('restoration4', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restoration4', to='app.restoration')),
            ],
        ),
    ]
